#! /bin/sh

#Clean lingering programs when reloaded
bash ~/.config/bspwm/clear &

# Variable Defines
color0=#3B4252
color4=#D8DEE9

# Make sure sxhkd is always running
while :; do
    if pgrep -x sxhkd > /dev/null; then
        true
    else
        sxhkd &
    fi
    sleep 5
done &

feh --bg-fill -Z --randomize ~/.config/wallapapers/* &
picom --config "$HOME/.config/picom.conf" &
setxkbmap -option grp:alt_shift_toggle us,ua &
xscreensaver &

#Fix Mouse cursor on startup 
xsetroot -cursor_name left_ptr

#Display config
bash ~/.config/bspwm/display_config.sh &

#Start polybar first
bash ~/.config/polybar/launch.sh &

#BSPWM Config
bspc config border_width        0
bspc config top_padding         35
bspc config right_padding       0
bspc config left_padding        0
bspc config bottom_padding      2
bspc config window_gap          2
bspc config top_monocle_padding  0
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0

bspc config focused_border_color "$color0"
bspc config normal_border_color  "$color0"
bspc config active_border_color  "$color0"
bspc config presel_feedback_color "$color4"
bspc config split_ratio          0.50
bspc config borderless_monocle   true  
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config external_rules_command "$HOME/.config/bspwm/external_rules.sh"

bspc desktop -f ^1

